# Generated by Django 4.1.6 on 2023-04-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserName', models.CharField(max_length=30)),
                ('DOB', models.DateTimeField(default=0.0005)),
                ('CourseName', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=30)),
                ('Password', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Register',
            },
        ),
    ]
